config/routes.rb
Rails.application.routes.draw do
  get 'password_resets/new'

  get 'password_resets/edit'

  get 'sessions/new'

  root 'static_pages#home' # => root_path
  get  '/help',    to: 'static_pages#help'
  get  '/about',   to: 'static_pages#about'
  get  '/contact', to: 'static_pages#contact'
  get  '/signup',  to: 'users#new'
  post '/signup',  to: 'users#create'
  
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  resources :users do
    member do
      # /users/:id/ ...
      get :following, :followers
      # GET /users/1/following => following action
      # GET /users/1/followers => followers action
    end
  end
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :microposts,          only: [:create, :destroy]
  resources :relationships,       only: [:create, :destroy]
  resources :attendances, only: [:create, :edit, :update, :destroy]
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    if logged_in?
      @micropost  = current_user.microposts.build
      @feed_items = current_user.feed.paginate(page: params[:page])
      @name = current_user.name
      @belongs = current_user.belongs
       # 日付はview側でeach文で回しつつ、日付部分のフォーマット変えて表示
      @dates = (Date.today.beginning_of_month..Date.today.end_of_month)
      @attendance = current_user.attendances.build
      @attendances = current_user.attendances
      @attendance_id = current_user.attendances.find_by(recorded_on: Date.today).id
      # @attendance_id = current_user.attendances.last.id だとnilになった。なんでか不明
      @user = current_user
    end

    # app/views/リソース名/アクション名.html.erb
    # app/views/static_pages/home.html.erb
  end

  def help
  end
  
  def about
    # 'app/views/static_pages/about.html.erb'
  end
  
  def contact
    # app/views/static_pages/contact.html.erb'
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
  def not_yet_attend?(day)
    day.strftime('%m/%d') == Date.today.strftime('%m/%d')
  end

# 出勤ボタン押したか？のヘルパー
  def attended?(day)
    # day.strftime('%a, %d %b %Y') == current_user.attendances.where(recorded_on: Date.today.strftime('%a, %d %b %Y')).recorded_on.strftime('%a, %d %b %Y')
    # whereは複数取り出す。find_byは一つ
    return if current_user.attendances.find_by(recorded_on: day.strftime('%a, %d %b %Y')).nil?
    # 真偽判定する以前にこの式のコードでエラー出る。だから、ここでこそ、returnの出番じゃないのか！！！recorded_onがから（nil）の場合は、returnで終了
    day.strftime('%a, %d %b %Y') == current_user.attendances.
    find_by(recorded_on: day.strftime('%a, %d %b %Y')).recorded_on.strftime('%a, %d %b %Y')

    # recorded_onのデータ型は？？
  end

  def leaved?(day)
    return if current_user.attendances.find_by(recorded_on: day.strftime('%a, %d %b %Y')).nil?
    current_user.attendances.find_by(recorded_on: day.strftime('%a, %d %b %Y')).leave_time.present?
  end 
  
  # こっちかな？
  # def leaved?(day)
  #   return if current_user.attendances.find_by(recorded_on: day.strftime('%a, %d %b %Y')).nil?
  #   current_user.attendances.find_by(recorded_on: day.strftime('%a, %d %b %Y')).leave_time.present?
  # end 


  #出勤の時、分を表示するヘルパー
  def attend_time(day)
    return if current_user.attendances.find_by(recorded_on: day.strftime('%a, %d %b %Y')).nil?
    current_user.attendances.find_by(recorded_on: day).attend_time.strftime("%H")
  end

  def attend_minute(day)
    return if current_user.attendances.find_by(recorded_on: day.strftime('%a, %d %b %Y')).nil?
    current_user.attendances.find_by(recorded_on: day).attend_time.strftime("%M")
  end


  #退勤の時、分を表示するヘルパー
  def leave_time(day)
    return if current_user.attendances.find_by(recorded_on: day.strftime('%a, %d %b %Y')).nil?
    current_user.attendances.find_by(recorded_on: day).leave_time.strftime("%H")
  end

  def leaved_minute(day)
    return if current_user.attendances.find_by(recorded_on: day.strftime('%a, %d %b %Y')).nil?
    current_user.attendances.find_by(recorded_on: day).leave_time.strftime("%M")
  end

  def worked_time(day)
    return if current_user.attendances.find_by(leave_time: day.beginning_of_day..day.end_of_day).nil?
    at = current_user.attendances.find_by(recorded_on: day).attend_time.strftime('%H%M')
    le = current_user.attendances.find_by(recorded_on: day).leave_time.strftime('%H%M')

      worked = at.to_i - le.to_i
      worked / 3600.0
  end

end

app/views/static_pages/about.html.erb
<% provide(:title, 'About') %>

<h1>About</h1>
<p>
  The <a href="http://railstutorial.jp/"><em>Ruby on Rails Tutorial</em></a>
  is a <a href="http://railstutorial.jp/book">book</a> and
  <a href="http://screencasts.railstutorial.org/">screencast series</a>
  to teach web development with
  <a href="http://rubyonrails.org/">Ruby on Rails</a>.
  This is the sample application for the tutorial.
</p>

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact') %>

<h1>Contact</h1>
<p>
  Contact the Ruby on Rails Tutorial about the sample app at the
  <a href="http://railstutorial.jp/contact">contact page</a>.
</p>

app/views/static_pages/help.html.erb
<% provide(:title, 'Help') %>

<h1>Help</h1>
<p>
  Get help on the Ruby on Rails Tutorial at the
  <a href="http://railstutorial.jp/help">Rails Tutorial help page</a>.
  To get help on this sample app, see the
  <a href="http://railstutorial.jp/book"><em>Ruby on Rails Tutorial</em>
  book</a>.
</p>

app/views/static_pages/home.html.erb
<% if logged_in? %>

<table>
  <table border="3"> 
  <tr>
    <th>時間管理票</th><td>指定勤務時間</th><th colspan="2">基本時間</th><th>初日</th>
  </tr>
  <tr>
    <td>所属 : <%= @belongs %></td><td>氏名 : <%= @name %></td><td>コード</td><td>出勤日数</td><td>締め</td>
  </tr>
  <tr>
    <td></td><td></td><td></td><td></td><td></td><td></td>
  </tr>
</table>

<table>
  <thead>
  <table border="3"> 
  <tr>
    <th rowspan="2">日付</th>
    <td rowspan="2">曜日</th>
    <th colspan="3">出社</th>
    <th colspan="3">退社</th>
    <th rowspan="2">在社時間</th>
    <th rowspan="2">備考</th>
  </tr>
  <tr>
    <td>時</td>
    <td>分</td>
    <td>出社</td>
    <td>時</td>
    <td>分</td>
    <td>退社</td>
  </tr>
  </thead>
  <tbody>
  <% @dates.each do |day| %>
  <tr>
    <td><%= day.strftime('%m/%d') %></td>
    <td><%= day.strftime('%a') %></td>
    <td><%= attend_time(day) %></td>
    <td><%= attend_minute(day) %></td>

    <td>
      <% if attended?(day) %>
  
      <% elsif not_yet_attend?(day) %>
        <%= button_to "出勤", attendances_path %>
      <% end %>
    </td>
    <td><%= leave_time(day) %></td>
    <td><%= leaved_minute(day) %></td>

    <td>
      <% if leaved?(day) %>
      
      <% elsif attended?(day) %>
        <%= button_to "退勤", attendance_path(id: @attendance_id), method: :put %>
      <% else %>

      <% end %>

    </td>

    <td><%= worked_time(day) %></td>
    <td></td>
  </tr>
  </tbody>
  <% end %>
</table>

<% else %>

<div class="center jumbotron">
  <h1>勤怠システム</h1>

  <%= link_to "ログイン", signup_path, class: "btn btn-lg btn-primary" %>
</div>

<% end %>          